// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";

Zora.test("Test endpoints", (function (t) {
        t.test("first test", (function (t) {
                t.ok(true, "It should make a test");
                
              }));
        
      }));

export {
  
}
/*  Not a pure module */
