// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Store from "../src/Store.bs.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Controller from "../src/Controller.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

Zora.test("Test endpoints", (function (t) {
        t.test("The Happy Path", (function (t) {
                var body = Caml_option.some(JSON.parse("\n      {\n        \"title\": \"Bread\",\n        \"ingredients\": \"Flour and Water\",\n        \"instructions\": \"Mix and Bake\"\n      }\n    "));
                var result = Controller.addRecipe(body);
                var id = Js_json.decodeString(Js_dict.get(Js_json.decodeObject(result), "id"));
                t.equal(id.length, 36, "The id should be the length of a uuid");
                var params = {};
                params["id"] = id;
                var result$1 = Controller.getRecipe(params);
                var json = JSON.stringify(result$1);
                var expected = "{\"id\":\"" + id + "\",\"title\":\"Bread\",\"ingredients\":\"Flour and Water\",\"instructions\":\"Mix and Bake\",\"tags\":[]}";
                t.equal(json, expected, "get recipe should match input");
                
              }));
        return Store.Reducer.dangerousResetState(undefined);
      }));

export {
  
}
/*  Not a pure module */
