// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";

Zora.test("testing_works", (function (t) {
        t.ok(true, "I told you it works");
        
      }));

export {
  
}
/*  Not a pure module */
