// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "@dusty-phillips/rescript-zora/src/Zora.bs.js";

function $$default(t) {
  t.test("testing works", (function (t) {
          t.ok(true, "I told you it works");
          return Zora.done(undefined);
        }));
  t.test("testing still works", (function (t) {
          t.ok(true, "I told you it works");
          return Zora.done(undefined);
        }));
  
}

export {
  $$default ,
  $$default as default,
  
}
/* No side effect */
