// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jzon from "rescript-jzon/src/Jzon.mjs";
import * as Zora from "zora";
import * as Curry from "rescript/lib/es6/curry.js";
import * as Store from "../src/Store.mjs";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Controller from "../src/Controller.mjs";
import * as Belt_Result from "rescript/lib/es6/belt_Result.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

Zora.test("Test endpoints", (function (t) {
        t.test("The Happy Path", (function (t) {
                var body = Caml_option.some(JSON.parse("\n      {\n        \"title\": \"Bread\",\n        \"ingredients\": \"Flour and Water\",\n        \"instructions\": \"Mix and Bake\"\n      }\n    "));
                var result = Controller.addRecipe(body);
                var id = Js_json.decodeString(Js_dict.get(Js_json.decodeObject(result), "id"));
                t.equal(id.length, 36, "The id should be the length of a uuid");
                var params = {};
                params["id"] = id;
                var result$1 = Controller.getRecipe(params);
                var actual = Belt_Result.getExn(Curry._1(Jzon.decode(Controller.recipeCodec), result$1));
                t.equal(actual.id, id, "should have same ids");
                t.equal(actual.title, "Bread", "should same title");
                t.equal(actual.ingredients, "Flour and Water", "have same ingredients");
                t.equal(actual.instructions, "Mix and Bake", "have same instructions");
                t.equal(actual.deleted, false, "should not be deleted");
                t.equal(actual.tags.length, 0, "Should not have any tags");
                var body$1 = Caml_option.some(JSON.parse("\n        {\n          \"recipeId\": \"" + id + "\",\n          \"tag\": \"Carbs\"\n        }\n        "));
                var result$2 = Controller.addTagToRecipe(body$1);
                var json = JSON.stringify(result$2);
                t.equal(json, "{\"success\":true}", "addTagToRecipe should return success");
                var result$3 = Controller.getRecipe(params);
                var actual$1 = Belt_Result.getExn(Curry._1(Jzon.decode(Controller.recipeCodec), result$3));
                t.equal(actual$1.id, id, "should have same ids");
                t.equal(actual$1.title, "Bread", "should same title");
                t.equal(actual$1.ingredients, "Flour and Water", "have same ingredients");
                t.equal(actual$1.instructions, "Mix and Bake", "have same instructions");
                t.equal(actual$1.deleted, false, "should not be deleted");
                t.equal(actual$1.tags.length, 1, "Should have one tag");
                t.equal(actual$1.tags[0], "Carbs", "First tag should be carbs");
                var params$1 = {};
                params$1["tag"] = "Carbs";
                var result$4 = Controller.getTag(params$1);
                var json$1 = JSON.stringify(result$4);
                var expected = "{\"recipes\":[{\"id\":\"" + id + "\",\"title\":\"Bread\"}]}";
                t.equal(json$1, expected, "tag should now have recipes");
                
              }));
        Store.Reducer.dangerousResetState(undefined);
        t.test("addRecipe missing attribute", (function (t) {
                var body = Caml_option.some(JSON.parse("{}"));
                var result = Controller.addRecipe(body);
                var json = JSON.stringify(result);
                t.equal(json, "{\"error\":\"Missing field \\\"title\\\" at .\"}", "There should be missing attributes");
                console.log(json);
                
              }));
        t.test("can't add tag to nonexistent recipe", (function (t) {
                var body = Caml_option.some(JSON.parse("\n        {\n          \"recipeId\": \"Not a Recipe\",\n          \"tag\": \"Carbs\"\n        }\n        "));
                var result = Controller.addTagToRecipe(body);
                var json = JSON.stringify(result);
                t.equal(json, "{\"error\":\"recipe does not exist\"}", "addTagToRecipe should return success");
                
              }));
        t.test("Can't get recipe that doesn't exist", (function (t) {
                var params = {};
                params["id"] = "Not a Recipe";
                var result = Controller.getRecipe(params);
                var json = JSON.stringify(result);
                t.equal(json, "{\"error\":\"unable to find that recipe\"}", "get recipe should match input");
                
              }));
        
      }));

export {
  
}
/*  Not a pure module */
