// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Uuid from "uuid";
import * as Store from "./Store.bs.js";
import * as Schema from "./Schema.bs.js";
import * as Express from "bs-express/src/Express.bs.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Resolvers from "./Resolvers.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as ExpressGraphql from "express-graphql";

var app = Express.express(undefined);

Express.App.use(app, Express.Middleware.json(undefined, undefined, undefined, undefined));

Express.App.useOnPath(app, "/graphql", ExpressGraphql.graphqlHTTP({
          schema: Schema.schema,
          graphiql: true,
          rootValue: Resolvers.rootValue
        }));

Express.App.get(app, "/", Express.Middleware.from(function (param, param$1, res) {
          var result = {};
          result["Hello"] = "World";
          return Express.$$Response.status(res, /* Ok */0).json(result);
        }));

Express.App.post(app, "/addRecipe", Express.Middleware.from(function (_next, req, res) {
          var jsonResponse = {};
          var jsonFields = Belt_Option.map(Belt_Option.flatMap(Caml_option.nullable_to_opt(req.body), Js_json.decodeObject), (function (jsonBody) {
                  return [
                          Belt_Option.flatMap(Js_dict.get(jsonBody, "title"), Js_json.decodeString),
                          Belt_Option.flatMap(Js_dict.get(jsonBody, "ingredients"), Js_json.decodeString),
                          Belt_Option.flatMap(Js_dict.get(jsonBody, "instructions"), Js_json.decodeString)
                        ];
                }));
          var exit = 0;
          if (jsonFields !== undefined) {
            var title = jsonFields[0];
            if (title !== undefined) {
              var ingredients = jsonFields[1];
              if (ingredients !== undefined) {
                var instructions = jsonFields[2];
                if (instructions !== undefined) {
                  var id = Uuid.v4();
                  Store.Reducer.dispatch({
                        TAG: /* AddRecipe */0,
                        id: id,
                        title: title,
                        ingredients: ingredients,
                        instructions: instructions
                      });
                  jsonResponse["id"] = id;
                } else {
                  exit = 1;
                }
              } else {
                exit = 1;
              }
            } else {
              exit = 1;
            }
          } else {
            exit = 1;
          }
          if (exit === 1) {
            jsonResponse["error"] = "missing attribute";
          }
          return res.json(jsonResponse);
        }));

Express.App.post(app, "/addTagToRecipe", Express.Middleware.from(function (_next, req, res) {
          var jsonResponse = {};
          var jsonFields = Belt_Option.map(Belt_Option.flatMap(Caml_option.nullable_to_opt(req.body), Js_json.decodeObject), (function (jsonBody) {
                  return [
                          Belt_Option.flatMap(Belt_Option.flatMap(Js_dict.get(jsonBody, "recipeId"), Js_json.decodeString), (function (id) {
                                  return Belt_MapString.get(Store.Reducer.getState(undefined).recipes, id);
                                })),
                          Belt_Option.flatMap(Js_dict.get(jsonBody, "tag"), Js_json.decodeString)
                        ];
                }));
          var exit = 0;
          if (jsonFields !== undefined) {
            var recipe = jsonFields[0];
            if (recipe !== undefined) {
              var tag = jsonFields[1];
              if (tag !== undefined) {
                jsonResponse["success"] = true;
                Store.Reducer.dispatch({
                      TAG: /* AddTag */1,
                      recipeId: recipe.id,
                      tag: tag
                    });
              } else {
                exit = 1;
              }
            } else {
              exit = 1;
            }
          } else {
            exit = 1;
          }
          if (exit === 1) {
            jsonResponse["error"] = "invalid request";
          }
          return res.json(jsonResponse);
        }));

Express.App.get(app, "/recipes/:id", Express.Middleware.from(function (_next, req, res) {
          var jsonResponse = {};
          var state = Store.Reducer.getState(undefined);
          var recipeOption = Belt_Option.flatMap(Belt_Option.flatMap(Js_dict.get(req.params, "id"), Js_json.decodeString), (function (id) {
                  return Belt_MapString.get(state.recipes, id);
                }));
          if (recipeOption !== undefined) {
            jsonResponse["id"] = recipeOption.id;
            jsonResponse["title"] = recipeOption.title;
            jsonResponse["ingredients"] = recipeOption.ingredients;
            jsonResponse["instructions"] = recipeOption.instructions;
            jsonResponse["tags"] = recipeOption.tags;
          } else {
            jsonResponse["error"] = "unable to find that recipe";
          }
          return res.json(jsonResponse);
        }));

Express.App.get(app, "/allTags", Express.Middleware.from(function (_next, _req, res) {
          var jsonResponse = {};
          jsonResponse["tags"] = Belt_MapString.keysToArray(Store.Reducer.getState(undefined).tags);
          return res.json(jsonResponse);
        }));

Express.App.get(app, "/tags/:tag", Express.Middleware.from(function (_next, req, res) {
          var jsonResponse = {};
          var state = Store.Reducer.getState(undefined);
          var taggedRecipesOption = Belt_Option.flatMap(Belt_Option.flatMap(Js_dict.get(req.params, "tag"), Js_json.decodeString), (function (tag) {
                  return Belt_MapString.get(state.tags, tag);
                }));
          if (taggedRecipesOption !== undefined) {
            var recipes = Belt_Array.map(Belt_Array.keep(Belt_Array.map(taggedRecipesOption.recipes, (function (id) {
                            return Belt_Option.map(Belt_MapString.get(state.recipes, id), (function (recipe) {
                                          var dict = {};
                                          dict["id"] = id;
                                          dict["title"] = recipe.title;
                                          return dict;
                                        }));
                          })), Belt_Option.isSome), (function (opt) {
                    return opt;
                  }));
            jsonResponse["recipes"] = recipes;
          } else {
            jsonResponse["error"] = "tag not found";
          }
          return res.json(jsonResponse);
        }));

var server = Express.App.listen(app, 3001, undefined, (function (param) {
        console.log("Example app listening at http://localhost:" + (3001).toString());
        
      }), undefined);

var port = 3001;

export {
  app ,
  port ,
  server ,
  
}
/* app Not a pure module */
