// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function hello(param) {
  return "hello world";
}

var rootValue = {
  hello: hello
};

exports.hello = hello;
exports.rootValue = rootValue;
/* No side effect */
