// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function recipeRxDbFeed(param) {
  return [];
}

function taggedRecipesRxDbFeed(param) {
  return [];
}

function setRecipe(param) {
  var recipe = param.recipe;
  return {
          id: recipe.id,
          title: recipe.title,
          ingredients: recipe.ingredients,
          instructions: recipe.instructions,
          tags: recipe.tags,
          updatedAt: Date.now(),
          deleted: recipe.deleted
        };
}

function setTaggedRecipes(param) {
  var taggedRecipes = param.taggedRecipes;
  return {
          tag: taggedRecipes.tag,
          recipes: taggedRecipes.recipes,
          updatedAt: Date.now(),
          deleted: taggedRecipes.deleted
        };
}

var rootValue = {
  recipeRxDbFeed: recipeRxDbFeed,
  taggedRecipesRxDbFeed: taggedRecipesRxDbFeed,
  setRecipe: setRecipe,
  setTaggedRecipes: setTaggedRecipes
};

exports.recipeRxDbFeed = recipeRxDbFeed;
exports.taggedRecipesRxDbFeed = taggedRecipesRxDbFeed;
exports.setRecipe = setRecipe;
exports.setTaggedRecipes = setTaggedRecipes;
exports.rootValue = rootValue;
/* No side effect */
