// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Graphql = require("graphql");

var schema = Graphql.buildSchema("\n  type Query {\n    hello: String\n  }\n");

exports.schema = schema;
/* schema Not a pure module */
