// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Graphql from "graphql";

var schema = Graphql.buildSchema("\n  type Recipe {\n    id: String!,\n    title: String!,\n    ingredients: String!,\n    instructions: String!,\n    tags: [String]!,\n    updatedAt: Float!,\n    deleted: Boolean!,\n\n  }\n\n  type TaggedRecipes {\n    tag: String!,\n    recipes: [String]!,\n    updatedAt: Float!,\n    deleted: Boolean!,\n  }\n\n  type Query {\n    recipeRxDbFeed(id: String!, minUpdatedAt: Float!, limit: Int!): [Recipe!]!\n\n    taggedRecipesRxDbFeed(\n      tag: String!\n      minUpdatedAt: Float!\n      limit: Int!\n    ): [TaggedRecipes!]!\n  }\n\n  input RecipeInput {\n    id: String!,\n    title: String!,\n    ingredients: String!,\n    instructions: String!,\n    tags: [String]!,\n    deleted: Boolean!,\n    updatedAt: Float\n\n  }\n\n  input TaggedRecipesInput {\n    tag: String!,\n    recipes: [String]!,\n    deleted: Boolean!,\n    updatedAt: Float\n  }\n\n  type Mutation {\n    setRecipe(recipe: RecipeInput!): Recipe!\n    setTaggedRecipes(taggedRecipes: TaggedRecipesInput!): TaggedRecipes!\n  }\n");

export {
  schema ,
  
}
/* schema Not a pure module */
